import type { Product } from "@/types";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Yerba Amanda Tradicional",
    description: "Yerba mate tradicional con un sabor intenso y equilibrado. Perfecta para cebadores exigentes.",
    price: 1850,
    image: "https://images.unsplash.com/photo-1582301172000-1b72abddd10b?w=400&q=80",
    category: "yerba",
    tag: "destacado",
    weight: "500g",
  },
  {
    id: "2",
    name: "Yerba Taragüi Con Palo",
    description: "Sabor suave y ahumado con palo. Ideal para largas jornadas en ronda.",
    price: 1650,
    image: "https://images.unsplash.com/photo-1609975031156-a626cd7001ef?w=400&q=80",
    category: "yerba",
    weight: "500g",
  },
  {
    id: "3",
    name: "Mate Calabaza Artesanal",
    description: "Mate de calabaza curado a mano, con terminación en metal dorado.",
    price: 4200,
    image: "https://images.unsplash.com/photo-1646233487430-cb90b0d61bf2?w=400&q=80",
    category: "mate",
    tag: "nuevo",
  },
  {
    id: "4",
    name: "Bombilla Alpaca Premium",
    description: "Bombilla de alpaca con filtro de acero inoxidable y cuerpo torneado.",
    price: 2800,
    image: "https://images.unsplash.com/photo-1675001077145-890585f3c151?w=400&q=80",
    category: "bombilla",
    tag: "destacado",
  },
  {
    id: "5",
    name: "Yerba CBSé Hierbas",
    description: "Blend de yerba con hierbas medicinales: menta, cedrón y burrito.",
    price: 1950,
    image: "https://images.unsplash.com/photo-1675001077188-809370ce3279?w=400&q=80",
    category: "yerba",
    weight: "500g",
  },
  {
    id: "6",
    name: "Combo Iniciación",
    description: "Set completo: yerba 500g + mate de calabaza + bombilla + limpiador.",
    price: 7500,
    image: "https://images.unsplash.com/photo-1585744259332-111384f5def9?w=400&q=80",
    category: "combos",
    tag: "oferta",
  },
  {
    id: "7",
    name: "Termo Stanley Clásico",
    description: "Termo de acero inoxidable de 1L. Mantiene la temperatura por 24hs.",
    price: 12900,
    image: "https://images.unsplash.com/photo-1675000958126-0dd0ebb6ae33?w=400&q=80",
    category: "accesorios",
    tag: "destacado",
  },
  {
    id: "8",
    name: "Mate Madera de Palo Santo",
    description: "Mate torneado en palo santo con aroma natural inigualable.",
    price: 5600,
    image: "https://images.unsplash.com/photo-1646233487430-cb90b0d61bf2?w=400&q=80",
    category: "mate",
  },
  {
    id: "9",
    name: "Yerba La Merced Elaborada",
    description: "Yerba premium con palo, elaborada y envejecida 12 meses.",
    price: 2200,
    image: "https://images.unsplash.com/photo-1582301172000-1b72abddd10b?w=400&q=80",
    category: "yerba",
    tag: "nuevo",
    weight: "500g",
  },
];

export const PRODUCT_CATEGORY_LABELS: Record<string, string> = {
  yerba: "Yerbas",
  bombilla: "Bombillas",
  mate: "Mates",
  accesorios: "Accesorios",
  combos: "Combos",
};
