import type { Product } from "@/types";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Yerba Amanda Tradicional",
    description: "Yerba mate tradicional con un sabor intenso y equilibrado. Perfecta para cebadores exigentes.",
    details: "Amanda Tradicional es una yerba con palo de corte grueso, elaborada en la provincia de Misiones. Su secado al estilo barbacuá le otorga un sabor profundo y ahumado. Ideal para mates largos en ronda. Se recomienda usar agua a 75–80°C y no enjuagar la primera cebada.",
    image: "https://images.unsplash.com/photo-1582301172000-1b72abddd10b?w=400&q=80",
    category: "yerba",
    tag: "recomendado",
    weight: "500g",
    origin: "Misiones, Argentina",
  },
  {
    id: "2",
    name: "Yerba Taragüi Con Palo",
    description: "Sabor suave y ahumado con palo. Ideal para largas jornadas en ronda.",
    details: "Taragüi Con Palo es una de las yerbas más consumidas de Argentina. Su blend equilibrado entre hoja y palo ofrece un sabor suave y constante, sin picos de amargor. Perfecta para quienes se inician en el mundo del mate y para reuniones donde se ceba durante horas.",
    image: "https://images.unsplash.com/photo-1609975031156-a626cd7001ef?w=400&q=80",
    category: "yerba",
    weight: "500g",
    origin: "Corrientes, Argentina",
  },
  {
    id: "3",
    name: "Mate Calabaza Artesanal",
    description: "Mate de calabaza curado a mano, con terminación en metal dorado.",
    details: "El mate de calabaza es el recipiente más tradicional de la cultura mateadora. Este ejemplar proviene de una calabaza secada de forma natural y curada artesanalmente con yerba mate molida durante 48 horas. Su boca metálica dorada evita que se astille y prolonga su vida útil. Capacidad aproximada: 150–180 ml.",
    image: "https://images.unsplash.com/photo-1646233487430-cb90b0d61bf2?w=400&q=80",
    category: "mate",
    tag: "nuevo",
    origin: "Corrientes, Argentina",
  },
  {
    id: "4",
    name: "Bombilla Alpaca Premium",
    description: "Bombilla de alpaca con filtro de acero inoxidable y cuerpo torneado.",
    details: "La bombilla de alpaca es la elección de los conocedores. Su aleación de cobre, zinc y níquel le otorga una durabilidad excepcional y una estética plateada elegante. El filtro de espiral en acero inoxidable retiene incluso la yerba más fina sin obstruirse. Largo total: 19 cm. Apta para lavar en lavavajillas.",
    image: "https://images.unsplash.com/photo-1675001077145-890585f3c151?w=400&q=80",
    category: "bombilla",
    tag: "recomendado",
  },
  {
    id: "5",
    name: "Yerba CBSé Hierbas",
    description: "Blend de yerba con hierbas medicinales: menta, cedrón y burrito.",
    details: "CBSé Hierbas es una yerba compuesta ideal para quienes buscan los beneficios del mate combinados con propiedades digestivas y relajantes. Su blend incluye menta peperina (digestiva), cedrón (calmante) y burrito (antiespasmódico). Tiene un sabor fresco y aromático, con menos amargor que las yerbas puras.",
    image: "https://images.unsplash.com/photo-1675001077188-809370ce3279?w=400&q=80",
    category: "yerba",
    weight: "500g",
    origin: "Entre Ríos, Argentina",
  },
  {
    id: "6",
    name: "Combo Iniciación",
    description: "Set completo para empezar: yerba 500g + mate de calabaza + bombilla + limpiador.",
    details: "El combo ideal para quien quiere iniciarse en el mundo del mate sin complicaciones. Incluye: yerba Amanda Tradicional 500g, mate de calabaza curado y listo para usar, bombilla de acero inoxidable con filtro de espiral, y un limpiador de bombilla de cerdas. Todo lo que necesitás para tu primer mate.",
    image: "https://images.unsplash.com/photo-1585744259332-111384f5def9?w=400&q=80",
    category: "combos",
    tag: "recomendado",
  },
  {
    id: "7",
    name: "Termo Stanley Clásico",
    description: "Termo de acero inoxidable de 1L. Mantiene la temperatura por 24hs.",
    details: "El Stanley Clásico es el termo favorito de los mateadores argentinos. Su doble pared de acero inoxidable 18/8 mantiene el agua caliente hasta 24 horas y fría hasta 48 horas. La boca ancha facilita la carga de hielo. No transpira, no retiene sabores y su tapa funciona también como vaso. Capacidad: 1 litro.",
    image: "https://images.unsplash.com/photo-1675000958126-0dd0ebb6ae33?w=400&q=80",
    category: "accesorios",
    tag: "recomendado",
    origin: "Seattle, EE.UU.",
  },
  {
    id: "8",
    name: "Mate Madera de Palo Santo",
    description: "Mate torneado en palo santo con aroma natural inigualable.",
    details: "El palo santo (Bulnesia sarmientoi) es una madera dura del Chaco argentino conocida por su aroma dulce y resinoso. Este mate torneado a mano no necesita curado: se lava, se llena de yerba y listo. Con el uso el aroma del palo santo se integra al sabor del mate creando una experiencia única. No apto para lavavajillas.",
    image: "https://images.unsplash.com/photo-1646233487430-cb90b0d61bf2?w=400&q=80",
    category: "mate",
    origin: "Chaco, Argentina",
  },
  {
    id: "9",
    name: "Yerba La Merced Elaborada",
    description: "Yerba premium con palo, elaborada y envejecida 12 meses.",
    details: "La Merced Elaborada es una yerba de alta gama producida en los mejores yerbatales de Misiones. Su proceso de elaboración incluye un envejecimiento de 12 meses en silos especiales, lo que reduce el amargor y potencia sus notas dulces y herbáceas. Corte fino, color verde intenso. Perfecta para el mate de la mañana.",
    image: "https://images.unsplash.com/photo-1582301172000-1b72abddd10b?w=400&q=80",
    category: "yerba",
    tag: "nuevo",
    weight: "500g",
    origin: "Misiones, Argentina",
  },
];

export const PRODUCT_CATEGORY_LABELS: Record<string, string> = {
  yerba: "Yerbas",
  bombilla: "Bombillas",
  mate: "Mates",
  accesorios: "Accesorios",
  combos: "Combos",
};
